### ISSUE TITLE
example was an error

### ISSUE THREAD

**Issue by YuK1Game** [php-promise/promise#1]
I ran the sample.
But that is an error.

```test.php
<?php
require_once('vendor/autoload.php');

use Promise\Promise;
use Promise\Processors\Resolver;
use Promise\Processors\Rejecter;

$promise = (new \Promise\Promise(function (Resolver $resolve, Rejecter $reject) {
    sleep(5);
    $resolve("Solved It!\n");
}))->then(function ($message) {
    echo $message;
});
```

Result errors.
```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Promise\Processors\Processor::{closure}(), 0 passed in \path\to\vendor\php-promise\promise\src\Context\Context.php on line 230 and exactly 1 expected in \path\to\async.php:11
Stack trace:
#0 \path\to\vendor\php-promise\promise\src\Context\Context.php(230): Promise\Processors\Processor::{closure}()
#1 [internal function]: Promise\Processors\Processor->Promise\Context\{closure}(Object(Promise\Context\Context), Object(Closure), NULL)
#2 \path\to\vendor\php-promise\promise\src\Context\Context.php(237): Threaded->synchronized(Object(Closure), Object(Promise\Context\Context), Object(Closure), NULL)
#3 \path\to\vendor\php-promise\promise\src\Processors\Processor.php(68): Promise\Processors\Processor->Promise\Context\{ in \path\to\async.php on line 11
```

Is the usage correct?

environment
Windows 10
PHP 7.2.14
pthreads 3.2.0

thanks

**Comment by tanigami** [comment]
+1

**Comment by m3m0r7** [comment]
@YuK1Game 
Thanks for your report!
And sorry for the late reply.

I'll fix this problem ASAP.

Thanks.

**Comment by m3m0r7** [comment]
I fixed this problem.
Try again the example to get correct result.
